-- MySQL Script generated by MySQL Workbench --
-- dom 26 nov 2023 22:15:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema companiaAerea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `AVION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AVION` (
  `matricula` CHAR(9) NOT NULL,
  `fabricante` VARCHAR(50) NOT NULL,
  `modelo` VARCHAR(75) NOT NULL,
  `capacidad` INT NOT NULL,
  `autonomia` INT NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `CATEGORIA_PROFESIONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CATEGORIA_PROFESIONAL` (
  `cod_categoria` CHAR(5) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PASAJERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PASAJERO` (
  `dni_pasajero` CHAR(9) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos` VARCHAR(20) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`dni_pasajero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `VUELO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VUELO` (
  `id_vuelo` CHAR(5) NOT NULL,
  `matricula` CHAR(9) NOT NULL,
  `origen` VARCHAR(50) NOT NULL,
  `destino` VARCHAR(50) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_vuelo`),
  INDEX `FK_VUELO_AVION` (`matricula` ASC) VISIBLE,
  CONSTRAINT `FK_VUELO_AVION`
    FOREIGN KEY (`matricula`)
    REFERENCES `AVION` (`matricula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `DISTRIBUCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DISTRIBUCION` (
  `dni_pasajero` CHAR(9) NOT NULL,
  `id_vuelo` CHAR(5) NOT NULL,
  `asiento` CHAR(4) NOT NULL,
  `clase` CHAR(3) NOT NULL,
  PRIMARY KEY (`dni_pasajero`, `id_vuelo`),
  INDEX `FK_DISTRIBUCION_VUELO` (`id_vuelo` ASC) VISIBLE,
  CONSTRAINT `FK_DISTRIBUCION_PASAJERO`
    FOREIGN KEY (`dni_pasajero`)
    REFERENCES `PASAJERO` (`dni_pasajero`),
  CONSTRAINT `FK_DISTRIBUCION_VUELO`
    FOREIGN KEY (`id_vuelo`)
    REFERENCES `VUELO` (`id_vuelo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PERSONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERSONAL` (
  `id_trabajador` CHAR(5) NOT NULL,
  `cod_categoria` CHAR(5) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellidos1` VARCHAR(20) NOT NULL,
  `apellidos2` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_trabajador`),
  INDEX `FK_PERSONAL_CATEGORIA` (`cod_categoria` ASC) VISIBLE,
  CONSTRAINT `FK_PERSONAL_CATEGORIA`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `CATEGORIA_PROFESIONAL` (`cod_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PUESTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PUESTO` (
  `id_trabajador` CHAR(5) NOT NULL,
  `id_vuelo` CHAR(5) NOT NULL,
  PRIMARY KEY (`id_trabajador`, `id_vuelo`),
  INDEX `FK_VUELO_PUESTO` (`id_vuelo` ASC) VISIBLE,
  CONSTRAINT `FK_TRABAJADOR_PUESTO`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `PERSONAL` (`id_trabajador`),
  CONSTRAINT `FK_VUELO_PUESTO`
    FOREIGN KEY (`id_vuelo`)
    REFERENCES `VUELO` (`id_vuelo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TELEFONO_PASAJERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONO_PASAJERO` (
  `dni_pasajero` CHAR(9) NOT NULL,
  `telefono_pasajero` CHAR(9) NOT NULL,
  PRIMARY KEY (`dni_pasajero`, `telefono_pasajero`),
  CONSTRAINT `TELEFONOPASAJERO_PASAJERO`
    FOREIGN KEY (`dni_pasajero`)
    REFERENCES `PASAJERO` (`dni_pasajero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TELEFONO_PERSONAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONO_PERSONAL` (
  `id_trabajador` CHAR(5) NOT NULL,
  `telefono` CHAR(9) NOT NULL,
  PRIMARY KEY (`id_trabajador`, `telefono`),
  CONSTRAINT `FK_TELEFONOPERS_TRABAJADOR`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `PERSONAL` (`id_trabajador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
